name: release

on:
  push:
    tags: ["*"]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install hatch-vcs
      - name: Build and publish
        run: |
          hatch build
          # hatch publish
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1